CREATE TABLE Cad_Usuario (
    PK_ID       SERIAL PRIMARY KEY,
    NOME        VARCHAR(100) NOT NULL,
    LOGIN       VARCHAR(50) NOT NULL,
    SENHA       VARCHAR(255) NOT NULL,
    SETOR       VARCHAR(50),
    SOBRE_NOME  VARCHAR(80),
    PLANTA      VARCHAR(50),
    EMAIL       VARCHAR(255),
    UNIQUE (LOGIN)
);

INSERT INTO Cad_Usuario (PK_ID, NOME, LOGIN, SENHA, PLANTA) VALUES (1, 'DDZL7', 'admin', '$2a$10$xDjekR3Ts0vGaq02eu3DR.xAllgW2bl4IibHLnIVEcGJ9Wo7nWS/2', 'Varginha');

CREATE SEQUENCE users_seq
    START 2
    INCREMENT 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
