CREATE TABLE Cad_Oem (
    ID_OEM BIGINT NOT NULL PRIMARY KEY,
    OEM VARCHAR(50) NOT NULL,
    UNIQUE (OEM)
);

CREATE SEQUENCE oem_seq
    START 1
    INCREMENT 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE Cad_Projeto (
    ID_PROJETO BIGINT NOT NULL PRIMARY KEY,
    PROJETO VARCHAR(50) NOT NULL,
    PRO_OEM VARCHAR(50),
    UNIQUE (PROJETO),
    CONSTRAINT FK_Cad_Projeto_Cad_Oem FOREIGN KEY(PRO_OEM) REFERENCES Cad_Oem(OEM)
);

CREATE SEQUENCE project_seq
    START 1
    INCREMENT 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE Cad_Material (
    ID_MATERIAL BIGINT NOT NULL PRIMARY KEY,
    MATERIAL BIGINT NOT NULL,
    DESC_MATERIAL VARCHAR(255) NULL,
    MAT_LINHA VARCHAR(50) NULL,
    MAT_PROJETO VARCHAR(50) NULL,
    N_DESENHO VARCHAR(100) NULL,
    N_PLANO VARCHAR(50) NULL,
    BPCS VARCHAR(10) NULL,
    META VARCHAR(10) NULL,
    OBSERVACAO VARCHAR(500) NULL,
    IMAGE VARCHAR(150) NULL,
    IMAGEROD VARCHAR(255) NULL,
    CONSTRAINT FK_Cad_Material_Cad_Linha FOREIGN KEY(MAT_LINHA) REFERENCES Cad_Linha(LINHA),
    CONSTRAINT FK_Cad_Material_Cad_Projeto FOREIGN KEY(MAT_PROJETO) REFERENCES Cad_Projeto(PROJETO)
);

CREATE SEQUENCE material_seq
    START 1
    INCREMENT 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
