CREATE TABLE DDZ_Controle (
    ID BIGINT PRIMARY KEY,
    MATERIAL VARCHAR(255) NOT NULL,
    DATA_BASE DATE NOT NULL,
    LINHA VARCHAR(255) NOT NULL,
    SCRAP_TOTAL DECIMAL(10,2) NOT NULL
);

CREATE SEQUENCE ddz_control_seq
    START 1
    INCREMENT 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE Problemas (
    ID BIGINT PRIMARY KEY,
    DESC_PROBLEMA VARCHAR(255) NULL
);

CREATE SEQUENCE problem_seq
    START 1
    INCREMENT 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE Causas (
    ID BIGINT PRIMARY KEY,
    DESC_CAUSA VARCHAR(255) NULL,
    ID_PROBLEMA_ID BIGINT NULL,
    CONSTRAINT Causas_ID_PROBLEMA_ID FOREIGN KEY (ID_PROBLEMA_ID) REFERENCES Problemas (ID)
);

CREATE SEQUENCE cause_seq
    START 1
    INCREMENT 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE DDZ (
    ID BIGINT PRIMARY KEY,
    ACAO_TOMADA VARCHAR(300) NULL,
    DATA_INPUT DATE NULL,
    HORA_INPUT TIME NULL,
    OBSERVACAO VARCHAR(300) NULL,
    TURNO VARCHAR(10) NULL,
    ID_CAUSA_ID BIGINT NULL,
    ID_M_MATERIAL BIGINT NULL,
    QTD_SCRAP FLOAT NULL,
    QTD_SCRAP_REAIS FLOAT NULL,
    QTD_SCRAP_KG FLOAT NULL,
    VELOCIDADE FLOAT NULL,
    PESO FLOAT NULL,
    DATA_REAL DATE NULL,
    PRIORIDADE INT NULL,
    PARTICIPANTES VARCHAR(255) NULL,
    RESPONSAVEL VARCHAR(50) NULL,
    DATA_CONCLUIDO DATE NULL,
    DATA_PLANO DATE NULL,
    FLAG CHAR(1) NULL,
    CONSTRAINT FK_DDZ_ID_CAUSA_ID FOREIGN KEY (ID_CAUSA_ID) REFERENCES Causas (ID),
    CONSTRAINT FK_DDZ_ID_M_MATERIAL FOREIGN KEY (ID_M_MATERIAL) REFERENCES Cad_Material (ID_MATERIAL)
);

CREATE SEQUENCE ddz_seq
    START 1
    INCREMENT 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
